{% set name = "torchmd-net" %}
{% set org = "torchmd" %}
{% set version = "2.5.0" %}
{% set sha256 = "82cdef271dadfb1f598711e777fd4b319f1c8a66f2520935c1cee5385cf3dfd0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  entry_points:
    - torchmd-train = torchmdnet.scripts.train:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=78
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - pytorch
    - pytorch_geometric
    - lightning
    - tqdm
    - numpy
    - ase

test:
  imports:
    - torchmdnet
  commands:
    - torchmd-train --help
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/torchmd/torchmd-net
  summary: TorchMD-NET provides state-of-the-art neural networks potentials for biomolecular systems
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefdoerr
