{% set version = "2.4.6" %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: torchmd-net
  version: {{ version }}

source:
  url: https://github.com/torchmd/torchmd-net/archive/{{ version }}.tar.gz
  sha256: 8bcd2474e08c5bc85fd6bde0f2b1ecea60a34be45d06b9df321d1408ad5a4aad

build:
  # Currently there is no pytorch 2.5.1 for Windows and CUDA 11.8. Only 12+. Same for aarch64.
  skip: true  # [(win or aarch64) and (cuda_compiler_version == '11.8')]
  entry_points:
    - torchmd-train = torchmdnet.scripts.train:main
  number: 4
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  rpaths:
    - lib/
    - {{ SP_DIR }}/torch/lib
  missing_dso_whitelist:
    - "*/c10.dll"         # [win]
    - "*/torch_cpu.dll"   # [win]
    - "*/c10_cuda.dll"    # [win]

requirements:
  build:
    - python                                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}        # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('cuda') }}                    # [cuda_compiler_version not in (undefined, 'None')]
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version not in (undefined, 'None')]
    - pytorch                                   # [build_platform != target_platform]
    - pytorch =*={{ torch_proc_type }}*         # [(build_platform != target_platform) or win]
    - cuda-cudart-dev                           # [(cuda_compiler_version or "").startswith("12")]
    - cuda-driver-dev                           # [(cuda_compiler_version or "").startswith("12") and linux]
    - libcufft-dev                              # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev                             # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev                             # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvrtc-dev                            # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev                           # [(cuda_compiler_version or "").startswith("12")]
    - libcusolver-dev                           # [(cuda_compiler_version or "").startswith("12")]
  host:
    - python
    - setuptools
    - pip
    - pytorch =*={{ torch_proc_type }}*
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version not in (undefined, 'None')]
    - cuda-cudart-dev                           # [(cuda_compiler_version or "").startswith("12")]
  run:
    - python
    - h5py
    - pytorch_geometric
    - lightning
    - tqdm
    - cuda-cudart                               # [(cuda_compiler_version or "").startswith("12")]
  run_constrained:
    - pytorch =*={{ torch_proc_type }}*

test:
  imports:
    - torchmdnet
  commands:
    - pip check
    - torchmd-train --help
    - pytest -v -s tests  # [py<3.12]
    # Pytorch compile does not support 3.12
    - pytest -v -k "not compile" -s tests  # [py>=3.12]
  requires:
    - pip
    - pytest
    # Needed by pytorch for the compile functionality
    - gxx  # [linux]
    - clang  # [osx]
  source_files:
    - tests
    - examples

about:
  home: https://github.com/torchmd/torchmd-net
  license: MIT
  license_file: README.md
  summary: 'State of the art Pytorch Neural Network Potentials (NNPs)'
  description: |
    TorchMD-NET provides state-of-the-art neural networks potentials (NNPs) and a mechanism to train them. It offers efficient and fast implementations of several NNPs and it is integrated in GPU-accelerated molecular dynamics code like ACEMD, OpenMM and TorchMD. TorchMD-NET exposes its NNPs as PyTorch modules.
  doc_url: https://github.com/torchmd/torchmd-net
  dev_url: https://github.com/torchmd/torchmd-net

extra:
  recipe-maintainers:
    - sef43
    - stefdoerr
    - RaulPPelaez
    - raimis
    - giadefa
