{% set name = "torchmd-net" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchmd_net-{{ version }}.tar.gz
  sha256: deb255d77720a04b0d2972e71977130da2ad918734c943fde72452d80bf83e92

build:
  skip: true  # [py<39]
  entry_points:
    - torchmd-train = torchmdnet.scripts.train:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=78
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.9
    - h5py
    - pytorch
    - pytorch_geometric
    - lightning
    - tqdm
    - numpy
    - triton  # [linux]
    - triton-windows  # [win]
    - ase

test:
  imports:
    - torchmdnet
  commands:
    - pip check
    - torchmd-train --help
  requires:
    - pip

about:
  summary: TorchMD-NET provides state-of-the-art neural networks potentials for biomolecular systems
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefdoerr
