azure:
  free_disk_space: true
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\bld
      MINIFORGE_HOME: C:\Miniforge
      SET_PAGEFILE: 'True'
bot:
  automerge: true
build_platform:
  linux_aarch64: linux_aarch64
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
test: native_and_emulated
