azure:
  free_disk_space: true
  settings_win:
    variables:
      SET_PAGEFILE: "True"
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: "2"
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native_and_emulated
