azure:
  free_disk_space: true
  settings_win:
    variables:
      SET_PAGEFILE: "True"
      CONDA_BLD_PATH: "C:\\bld"
      MINIFORGE_HOME: "C:\\Miniforge"
build_platform:
  linux_aarch64:
  osx_arm64:
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
provider:
  linux_aarch64: azure
test: native_and_emulated
